# Handle git submodules yourself
git:
  submodules: false

services:
  - postgresql

addons:
  sonarcloud:
    organization: "$SONAR_ORG"
    token: "$SONAR_TOKEN"
  postgresql: "9.6"

sudo: required
language: java

jdk:
  - openjdk8

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - psql -c 'create database mydb;' -U postgres
  - psql -c "CREATE USER dbuser WITH PASSWORD 'postgres';" -U postgres

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn install -Dmaven.test.skip=true
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
